import React from 'react'
import { Link } from "react-router-dom";
import ProductPage from "../common/ProductPage" ;

const Beauty = () => {
  const beauty = [
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://ahika.in/cdn/shop/products/vkskd1099-f_2.jpg?v=1695212270&width=1445",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "/gown.jpg",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "/kurti.png",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "/kurti-1.png",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "/kurti-2.png",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "/kurti-4.png",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "/lehenga.png",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "/lehenga-2.png",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "/partyware.png",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "/Salwar-suits.jpg",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "/skurti-3.png",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "/suit.jpg",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://www.ahalyaa.com/cdn/shop/products/17716144-1_292e5a5e-afb6-4389-852e-8cac45823411.png?v=1680617155",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://www.libas.in/cdn/shop/files/20158O_400x.jpg?v=1714549501",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://www.sassafras.in/cdn/shop/products/SHSET95383-1.jpg?v=1667914787",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://img.tatacliq.com/images/i8/437Wx649H/MP000000014448565_437Wx649H_202209141323411.jpeg",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://okhai.org/cdn/shop/files/0739W03-J54-YE_1_263x.jpg?v=1694778596",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://m.media-amazon.com/images/I/81QVZDAlz9L._AC_UY1100_.jpg",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://www.libas.in/cdn/shop/files/33151O_400x.jpg?v=1714548669",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://images.meesho.com/images/products/376287769/mj41u_512.jpg",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://imagescdn.pantaloons.com/img/app/product/4/432139-2745654.jpg?q=75&auto=format&w=412&h=621",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://i.ebayimg.com/images/g/OpAAAOSwfF5i24kx/s-l1200.jpg",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://stilento.com/cdn/shop/products/green-cotton-kurta-with-palazzo-for-women-stilento-1.jpg?v=1662795223",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://www.inddus.com/cdn/shop/products/women-grey-pink-ethnic-printed-kurta-with-palazzos-258268.png?v=1659247959",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://www.textileinfomedia.com/img/eazj/women-straight-multicolor-kurta-palazzo-full.jpg",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://rukminim2.flixcart.com/image/850/1000/l37mtu80/ethnic-set/t/c/8/l-new-morpichh-royal-export-original-imagecf7zfr2usyr.jpeg?q=90&crop=false",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://rukminim2.flixcart.com/image/850/1000/l0mr7gw0/ethnic-set/p/e/n/m-palazoo-set-kenix-world-original-imagcdtgh3ra7czp.jpeg?q=90&crop=false",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
    {
      sponser: "Sponsored",
      prize: "₹2,999",
      discountPrize: "₹699",
      offer: "76% off",
      brandName: "Klosia",
      name: "Women Viscose Rayon Kurta...",
      src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREBK7FcyzGTdzEd9nN_Z3Qgf_T4LY5KkYj7w&usqp=CAU",
      sizes: ["S", "L", "M", "XL", "XXL"],
    },
  ];
  return (
    <div className="flex flex-col gap-0  w-full  ">
      <div className="grid grid-cols-1  gap-7 place-items-start  m-[2rem]  border-bl  bg-white h-auto md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
        {beauty.map((curElem, index) => {
          return <ProductPage key={index} product={curElem} />;
        })}
      </div>
    </div>
  );
}

export default Beauty